In [9]:
import pandas as pd
import numpy as np

file_path = "Lab Session Data.xlsx"
sheet_name = "Purchase data"
data = pd.read_excel(file_path, sheet_name=sheet_name)

A = data.iloc[:, 1:4].apply(pd.to_numeric, errors='coerce').values


C = data.iloc[:, 4].apply(pd.to_numeric, errors='coerce').values

A = np.nan_to_num(A)
C = np.nan_to_num(C)


print("Matrix A (Feature Matrix):\n", A)
print("\nMatrix C (Payment Vector):\n", C)


vector_space_dimensionality = A.shape[1]
print(f"Dimensionality of the vector space: {vector_space_dimensionality}")


num_vectors = A.shape[0]
print(f"Number of vectors in the vector space: {num_vectors}")


rank_of_A = np.linalg.matrix_rank(A)
print(f"Rank of Matrix A: {rank_of_A}")


A_pseudo_inverse = np.linalg.pinv(A)
print("Pseudo-Inverse of A:\n", A_pseudo_inverse)


X = A_pseudo_inverse @ C
print("Cost of each product (X):")
for i, cost in enumerate(X, start=1):
    print(f"Product {i}: Rs. {cost:.2f}")



Matrix A (Feature Matrix):
 [[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]

Matrix C (Payment Vector):
 [386 289 393 110 280 167 271 274 148 198]
Dimensionality of the vector space: 3
Number of vectors in the vector space: 10
Rank of Matrix A: 3
Pseudo-Inverse of A:
 [[-0.01008596 -0.03124505  0.01013951  0.0290728   0.0182907   0.01161794
  -0.00771348  0.00095458  0.01743623 -0.00542016]
 [ 0.09059668  0.07263726  0.03172933 -0.09071908 -0.01893196 -0.06926996
   0.05675464  0.03152577 -0.07641966  0.00357352]
 [ 0.00299878  0.15874243 -0.05795468 -0.06609024 -0.06295043  0.03348017
   0.01541831 -0.01070461  0.00029003  0.05938755]]
Cost of each product (X):
Product 1: Rs. 1.00
Product 2: Rs. 55.00
Product 3: Rs. 18.00


In [10]:
import pandas as pd
import numpy as np

# Load the data from the "Purchase data" worksheet
file_path = "Lab Session Data.xlsx"
sheet_name = "Purchase data"
data = pd.read_excel(file_path, sheet_name=sheet_name)

# Extract A (Feature Matrix) - Selecting only product quantity columns (Candies, Mangoes, Milk Packets)
A = data.iloc[:, 1:4].apply(pd.to_numeric, errors='coerce').values

# Extract C (Target Vector) - Payment (Rs.)
C = data.iloc[:, 4].apply(pd.to_numeric, errors='coerce').values

# Handle missing values
A = np.nan_to_num(A)
C = np.nan_to_num(C)

# Display extracted matrices
print("Matrix A (Feature Matrix):\n", A)
print("\nMatrix C (Payment Vector):\n", C)

# Compute model vector X for predicting product costs using X = A^+ * C
X = A_pseudo_inverse @ C
print("Model Vector X (Predicted Cost per Unit of Each Product):")
for i, cost in enumerate(X, start=1):
    print(f"Product {i}: Rs. {cost:.2f}")

Matrix A (Feature Matrix):
 [[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]

Matrix C (Payment Vector):
 [386 289 393 110 280 167 271 274 148 198]
Model Vector X (Predicted Cost per Unit of Each Product):
Product 1: Rs. 1.00
Product 2: Rs. 55.00
Product 3: Rs. 18.00


In [13]:
import pandas as pd
import numpy as np

# Load the data from the "Purchase data" worksheet
file_path = "Lab Session Data.xlsx"
sheet_name = "Purchase data"
data = pd.read_excel(file_path, sheet_name=sheet_name)

# Extract A (Feature Matrix) - Selecting only product quantity columns (Candies, Mangoes, Milk Packets)
A = data.iloc[:, 1:4].apply(pd.to_numeric, errors='coerce').values

# Extract C (Target Vector) - Payment (Rs.)
C = data.iloc[:, 4].apply(pd.to_numeric, errors='coerce').values

# Handle missing values
A = np.nan_to_num(A)
C = np.nan_to_num(C)

# Categorize customers as RICH or POOR based on Payment
labels = np.where(C > 200, "RICH", "POOR")
data["Category"] = labels

# Simple rule-based classification
print("Updated Data with Category:\n", data[["Customer", "Category"]])

Updated Data with Category:
   Customer Category
0      C_1     RICH
1      C_2     RICH
2      C_3     RICH
3      C_4     POOR
4      C_5     RICH
5      C_6     POOR
6      C_7     RICH
7      C_8     RICH
8      C_9     POOR
9     C_10     POOR
